### PR TITLE
y

### PR DESCRIPTION
**Pull request by XLCharlie**

### CODE REVIEW

**Comment by Ghostfacefave** [comment]
Do you want to be part of my development team? I might start coding again but I will need some help because they are patching so much so quickly. I do not know if you are familiar with coding but if you are respond to this with your decision. thank you and bye.

**Comment by XLCharlie** [comment]
I would love to join your development team, but I am going to struggle with time constraints due to my school work.

**Comment by XLCharlie** [comment]
(And yes, I am in school.)

**Comment by Ghostfacefave** [comment]
We can have a meeting and maybe talk about developing new choices for how many tokens you get for each hack and try to make a max token bypasser. It would be phenomenal if we could. Let’s max out our limits

**Pull request closed without merging**
